# Generated by Django 5.0.7 on 2024-11-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='protein_sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq_info', models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=10000000)),
                ('protein_sequence', models.CharField(max_length=10000000)),
            ],
        ),
    ]
