# Generated by Django 5.0.7 on 2024-11-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprotein', '0002_proteinproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinproperties',
            name='extinction_coefficient',
            field=models.CharField(max_length=255),
        ),
    ]
