# Generated by Django 5.0.7 on 2024-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna_sequence',
            name='seq_info',
            field=models.CharField(default='default_value', max_length=10000000),
        ),
        migrations.AlterField(
            model_name='dna_sequence',
            name='dna_sequence',
            field=models.CharField(max_length=10000000),
        ),
    ]
