# Generated by Django 5.0.7 on 2024-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dna_sequence_seq_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna_sequence',
            name='seq_info',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=10000000),
        ),
    ]
