# Generated by Django 5.0.7 on 2024-11-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dna_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dna_info',
            old_name='dna',
            new_name='dna_sequence',
        ),
    ]
